runtime: python37
entrypoint: gunicorn -t 300 -b :$PORT server:app

runtime_config:
  python_version: 3

automatic_scaling:
    max_concurrent_requests: 40
    min_idle_instances: 0
    max_idle_instances: 1
    min_pending_latency: 10s
    max_pending_latency: 15s

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

